export const INCREMENT_COUNTER='INCREMENT_COUNTER'

export const DECREMENT_COUNTER='DECREMENT_COUNTER'

// Fruit

export const GET_DATA = 'GET_DATA'

export const DELETE_DATA = 'DELETE_DATA'

export const ERROR_DATA = 'ERROR_DATA'

export const PUT_DATA = 'PUT_DATA'

export const ADD_DATA = 'ADD_DATA'

export const LOADING_FRUIT = 'LOADING_FRUIT'

//vegetable

export const VEGETABLE_GET = 'VEGETABLE_GET'

export const VEGETABLE_DELETE = 'VEGETABLE_DELETE'

export const VEGETABLE_PUT = 'VEGETABLE_PUT'

export const VEGETABLE_ADD = 'VEGETABLE_ADD'

export const VEGETABLE_ERROR = 'VEGETABLE_ERROR'

export const VEGETABLE_LOADING = 'VEGETABLE_LOADING'



